import clsx from "clsx";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "tailwindcss/tailwind.css";
import "react-toastify/dist/ReactToastify.css"
import { Slide, ToastContainer } from "react-toastify";

const poppins = Poppins({
  subsets: ["latin"],
  style: "normal",
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(poppins.className, "bg-[#1f2335] text-[#c0caf5]")}>
        {children}
        <ToastContainer
          position="top-center"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
          transition={Slide}
          progressStyle={{ backgroundColor: "#4fd6be" }}
          toastStyle={{ backgroundColor: "#3b4261", padding: "none", margin: "none", maxWidth: "320px !important", width: "80% !important" }}
          className={poppins.className}
        />
      </body>
    </html>
  );
}
